project: 
  type: website

website:
  title: "Bethany Ball Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/your_url
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Bethany Ball 2024©"
    right: 
      - icon: linkedin
        href: www.linkedin.com/in/bethany-c-ball

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "DS250 Projects"
        file: projects.qmd
      - text: "My Resume"
        file: resume.qmd
      
  sidebar:
    - title: "DS 250 Projects"
      style: "docked"
      background: light
      contents:
        - text: " "
          file: projects.qmd
        - text: "---"
        - text: "Project 1"
          file: Projects/project1.qmd
        - text: "What’s in a name?"
        - text: "Project 2"
          file: Projects/project2.qmd
        - text: "TLate flights and missing data (JSON files)"
        - text: "Project 3"
          file: Projects/project3.qmd
        - text: "TFinding relationships in baseball."
        - text: "Project 4"
          file: Projects/project4.qmd
        - text: "Can you predict that?"
        - text: "Project 5"
          file: Projects/project5.qmd
        - text: "The war with Star Wars."
        #continue the pattern if you need more links
        #copy paste from title and keep it indented to sidebar to add additonal sidebar navigation for other pages

format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



